#!/bin/bash
# Simple performance comparison guide

echo "========================================="
echo "How to Compare C++ vs Python Performance"
echo "========================================="
echo ""
echo "METHOD 1: Side-by-Side Comparison (Recommended)"
echo "-----------------------------------------------"
echo "1. Open TWO terminal windows"
echo ""
echo "2. In Terminal 1, run C++ version:"
echo "   ./build/TradingEngine"
echo ""
echo "3. In Terminal 2, run Python version:"
echo "   python3 main.py"
echo ""
echo "4. Let both run for 1-2 minutes"
echo ""
echo "5. Press Ctrl+C in BOTH terminals to stop"
echo ""
echo "6. Compare these metrics in the final output:"
echo "   - 'Total messages processed'"
echo "   - 'Messages per second'"
echo "   - 'Average processing time'"
echo ""
echo "========================================="
echo "Key Metrics to Compare:"
echo "========================================="
echo ""
echo "1. CONNECTION TIME"
echo "   Time from start to first message"
echo "   Lower is better"
echo ""
echo "2. AVERAGE PROCESSING TIME"
echo "   Time to process each message"
echo "   Lower is better"
echo "   Expected: C++ should be 5-50x faster"
echo ""
echo "3. MESSAGES PER SECOND"
echo "   Throughput capability"
echo "   Higher is better"
echo "   Expected: C++ should handle more"
echo ""
echo "4. TOTAL MESSAGES PROCESSED"
echo "   Total messages in same time period"
echo "   Higher is better"
echo ""
echo "========================================="
echo "Expected Results:"
echo "========================================="
echo "C++ should show:"
echo "  ✓ Faster connection time"
echo "  ✓ Lower average processing time (0.01-0.1ms)"
echo "  ✓ Higher messages per second"
echo "  ✓ More total messages processed"
echo "Python should show:"
echo "  ✓ Still good performance for most use cases"
echo "  ✓ Easier to modify and debug"
echo "========================================="
echo "Ready to compare? Open two terminals and follow the steps above!"


